### ISSUE TITLE
Refactor Environment Variable (process.env.API_KEY)

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/node-async-weather#1]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

**Are you interested in Node JS, and/or APIs? Then you've come to the right project!** This command line app allows a user to type in a location, then pulls weather data from [OpenWeatherMap's API](http://openweathermap.org/) and returns it to the user. 

_If React JS, Node JS, APIs, HTML, Javascript, Webpack, Express, and/or SASS/CSS is more your thing, check out my other Hacktoberfest Project: [React-Weather-App](https://github.com/bmorelli25/React-Weather-App)! There are numerous [issues](https://github.com/bmorelli25/React-Weather-App/issues) to be solved - for all programming levels!_

**Your task:** Environment variables! Currently the environment variable `API_KEY` is passed into to projected via the command prompt. While this isn't a bad thing, it would be easier if a `.env` file was created and utilized with [dotenv](https://github.com/bkeepers/dotenv). 

Don't hesitate to reach out with questions, or if you need help understanding the code!

**Have an idea for a different improvement?** Awesome. I'll be opening up new issues all throughout Hacktoberfest - and please feel free to do the same! Want to implement a new feature, or found a bug? Open a new issue and start writing code!!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by kylec32** [comment]
I would be happy to take a look at this.

**Comment by bmorelli25** [comment]
Hey @kylec32! That be great, thanks! If you need help getting the app up and running, be sure to checkout the [readme](https://github.com/bmorelli25/node-async-weather/blob/master/README.md). 

Don't hesitate to ask if you run into questions.

Also, please feel free to open a new issue if you (or anyone else) runs into any improvements or changes they want to make!

**Comment by bmorelli25** [comment]
#3 Merged
