### ISSUE TITLE
Utilize OpenWeatherMap's API to return additional weather data (yargs, API, node)

### ISSUE THREAD

**Issue by bmorelli25** [bmorelli25/node-async-weather#2]
Hello [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!

**Are you interested in Node JS, and/or APIs? Then you've come to the right project!** This command line app allows a user to type in a location, then pulls weather data from [OpenWeatherMap's API](http://openweathermap.org/) and returns it to the user.

_If React JS, Node JS, APIs, HTML, Javascript, Webpack, Express, and/or SASS/CSS is more your thing, check out my other Hacktoberfest Project: [React-Weather-App](https://github.com/bmorelli25/React-Weather-App)! There are numerous [issues](https://github.com/bmorelli25/React-Weather-App/issues) to be solved - for all programming levels!_

**Your task:** Utilize OpenWeatherMaps API and return even more great data to the user. Using the [5 day/3 hour API](http://openweathermap.org/forecast5), return the 5 day forecast for the searched city if a user uses the `-f` flag or `-forecast` command. For help on how to do this, you can see my previous project [node-password-manager/app.js](https://github.com/bmorelli25/node-password-manager/blob/master/app.js).

Don't hesitate to reach out with questions, or if you need help understanding the code!

**Have an idea for a different improvement?** Awesome. I'll be opening up new issues all throughout Hacktoberfest - and please feel free to do the same! Want to implement a new feature, or found a bug? Open a new issue and start writing code!!

_PS: This project utilizes a `.editorconfig` file. This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the `.editorconfig` file. For more information, check out [editorconfig.org](http://editorconfig.org/)._

**Comment by wimpykid26** [comment]
@bmorelli25 Can I work on this?. I used the OpenWeatherMap API for something similar not too long ago in https://github.com/osdc/osdc-bot

**Comment by m5r** [comment]
#5

**Comment by martindavid** [comment]
I would like to contribute on this @bmorelli25

**Comment by bmorelli25** [comment]
Closing this issue as we already have two great pull requests. @martindavid, please feel free to open a new issue and contribute in another way! I'm more than happy to help you come up with a new idea or two.
